// Generated by `supabase gen types typescript` (via MCP) for project kihctocqvuewjxmpoxcw.
// Regenerate after any schema change. Do not hand-edit.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      action_log: {
        Row: {
          action_type: string
          actor: string
          after_state: Json | null
          before_state: Json | null
          build_id: string | null
          cost_cents: number | null
          created_at: string
          error: string | null
          event_id: string | null
          external_ref: string | null
          id: string
          rule_id: string | null
          status: string
          summary: string
        }
        Insert: {
          action_type: string
          actor: string
          after_state?: Json | null
          before_state?: Json | null
          build_id?: string | null
          cost_cents?: number | null
          created_at?: string
          error?: string | null
          event_id?: string | null
          external_ref?: string | null
          id?: string
          rule_id?: string | null
          status: string
          summary: string
        }
        Update: {
          action_type?: string
          actor?: string
          after_state?: Json | null
          before_state?: Json | null
          build_id?: string | null
          cost_cents?: number | null
          created_at?: string
          error?: string | null
          event_id?: string | null
          external_ref?: string | null
          id?: string
          rule_id?: string | null
          status?: string
          summary?: string
        }
        Relationships: []
      }
      agent_runs: {
        Row: {
          agent_id: string
          cost_cents: number | null
          error: string | null
          finished_at: string | null
          id: string
          input: Json | null
          output: Json | null
          started_at: string
          status: string
          tokens_used: number | null
          trigger: string
        }
        Insert: {
          agent_id: string
          cost_cents?: number | null
          error?: string | null
          finished_at?: string | null
          id?: string
          input?: Json | null
          output?: Json | null
          started_at?: string
          status?: string
          tokens_used?: number | null
          trigger: string
        }
        Update: {
          agent_id?: string
          cost_cents?: number | null
          error?: string | null
          finished_at?: string | null
          id?: string
          input?: Json | null
          output?: Json | null
          started_at?: string
          status?: string
          tokens_used?: number | null
          trigger?: string
        }
        Relationships: []
      }
      agents: {
        Row: {
          build_scope: string
          config: Json
          created_at: string
          current_task: string | null
          description: string | null
          id: string
          is_enabled: boolean
          last_result: string | null
          last_run_at: string | null
          name: string
          schedule_cron: string | null
          slug: string
          status: string
          updated_at: string
        }
        Insert: {
          build_scope?: string
          config?: Json
          created_at?: string
          current_task?: string | null
          description?: string | null
          id?: string
          is_enabled?: boolean
          last_result?: string | null
          last_run_at?: string | null
          name: string
          schedule_cron?: string | null
          slug: string
          status?: string
          updated_at?: string
        }
        Update: {
          build_scope?: string
          config?: Json
          created_at?: string
          current_task?: string | null
          description?: string | null
          id?: string
          is_enabled?: boolean
          last_result?: string | null
          last_run_at?: string | null
          name?: string
          schedule_cron?: string | null
          slug?: string
          status?: string
          updated_at?: string
        }
        Relationships: []
      }
      approvals: {
        Row: {
          action_spec: Json
          build_id: string | null
          created_at: string
          decided_at: string | null
          decided_by: string | null
          description: string | null
          event_id: string | null
          expires_at: string | null
          id: string
          preview: Json | null
          risk: string
          rule_id: string | null
          status: string
          title: string
        }
        Insert: {
          action_spec: Json
          build_id?: string | null
          created_at?: string
          decided_at?: string | null
          decided_by?: string | null
          description?: string | null
          event_id?: string | null
          expires_at?: string | null
          id?: string
          preview?: Json | null
          risk?: string
          rule_id?: string | null
          status?: string
          title: string
        }
        Update: {
          action_spec?: Json
          build_id?: string | null
          created_at?: string
          decided_at?: string | null
          decided_by?: string | null
          description?: string | null
          event_id?: string | null
          expires_at?: string | null
          id?: string
          preview?: Json | null
          risk?: string
          rule_id?: string | null
          status?: string
          title?: string
        }
        Relationships: []
      }
      briefings: {
        Row: {
          body: string
          created_at: string
          generated_for: string
          headline: string
          id: string
          kind: string
          model: string | null
          priorities: Json
          tokens_used: number | null
        }
        Insert: {
          body: string
          created_at?: string
          generated_for?: string
          headline: string
          id?: string
          kind?: string
          model?: string | null
          priorities?: Json
          tokens_used?: number | null
        }
        Update: {
          body?: string
          created_at?: string
          generated_for?: string
          headline?: string
          id?: string
          kind?: string
          model?: string | null
          priorities?: Json
          tokens_used?: number | null
        }
        Relationships: []
      }
      builds: {
        Row: {
          color: string
          created_at: string
          github_repo: string | null
          health_score: number
          id: string
          is_active: boolean
          mrr_target_cents: number
          name: string
          revenue_model: string | null
          slug: string
          sort_order: number
          stage: string
          updated_at: string
        }
        Insert: {
          color?: string
          created_at?: string
          github_repo?: string | null
          health_score?: number
          id?: string
          is_active?: boolean
          mrr_target_cents?: number
          name: string
          revenue_model?: string | null
          slug: string
          sort_order?: number
          stage?: string
          updated_at?: string
        }
        Update: {
          color?: string
          created_at?: string
          github_repo?: string | null
          health_score?: number
          id?: string
          is_active?: boolean
          mrr_target_cents?: number
          name?: string
          revenue_model?: string | null
          slug?: string
          sort_order?: number
          stage?: string
          updated_at?: string
        }
        Relationships: []
      }
      connections: {
        Row: {
          config: Json
          created_at: string
          description: string | null
          display_name: string
          id: string
          last_sync_at: string | null
          last_sync_status: string | null
          provider: string
          status: string
          sync_frequency: string | null
          updated_at: string
        }
        Insert: {
          config?: Json
          created_at?: string
          description?: string | null
          display_name: string
          id?: string
          last_sync_at?: string | null
          last_sync_status?: string | null
          provider: string
          status?: string
          sync_frequency?: string | null
          updated_at?: string
        }
        Update: {
          config?: Json
          created_at?: string
          description?: string | null
          display_name?: string
          id?: string
          last_sync_at?: string | null
          last_sync_status?: string | null
          provider?: string
          status?: string
          sync_frequency?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      decisions: {
        Row: {
          build_id: string | null
          context: Json
          created_at: string
          id: string
          kind: string
          outcome: string | null
          outcome_at: string | null
          postmortem: Json | null
          postmortem_at: string | null
          premortem: Json | null
          premortem_at: string | null
          ref_id: string | null
          ref_type: string | null
          title: string
          updated_at: string
        }
        Insert: {
          build_id?: string | null
          context?: Json
          created_at?: string
          id?: string
          kind: string
          outcome?: string | null
          outcome_at?: string | null
          postmortem?: Json | null
          postmortem_at?: string | null
          premortem?: Json | null
          premortem_at?: string | null
          ref_id?: string | null
          ref_type?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          build_id?: string | null
          context?: Json
          created_at?: string
          id?: string
          kind?: string
          outcome?: string | null
          outcome_at?: string | null
          postmortem?: Json | null
          postmortem_at?: string | null
          premortem?: Json | null
          premortem_at?: string | null
          ref_id?: string | null
          ref_type?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: []
      }
      events: {
        Row: {
          actor: string
          build_id: string | null
          created_at: string
          entity_id: string | null
          entity_type: string | null
          id: string
          payload: Json
          processed: boolean
          processed_at: string | null
          type: string
        }
        Insert: {
          actor?: string
          build_id?: string | null
          created_at?: string
          entity_id?: string | null
          entity_type?: string | null
          id?: string
          payload?: Json
          processed?: boolean
          processed_at?: string | null
          type: string
        }
        Update: {
          actor?: string
          build_id?: string | null
          created_at?: string
          entity_id?: string | null
          entity_type?: string | null
          id?: string
          payload?: Json
          processed?: boolean
          processed_at?: string | null
          type?: string
        }
        Relationships: []
      }
      expenses: {
        Row: {
          ai_categorized: boolean
          amount_cents: number
          build_id: string | null
          category: string
          created_at: string
          currency: string
          external_id: string | null
          id: string
          is_recurring: boolean
          notes: string | null
          receipt_path: string | null
          recurrence: string | null
          source: string
          spent_on: string
          tax_deductible: boolean | null
          updated_at: string
          vendor: string
        }
        Insert: {
          ai_categorized?: boolean
          amount_cents: number
          build_id?: string | null
          category: string
          created_at?: string
          currency?: string
          external_id?: string | null
          id?: string
          is_recurring?: boolean
          notes?: string | null
          receipt_path?: string | null
          recurrence?: string | null
          source?: string
          spent_on?: string
          tax_deductible?: boolean | null
          updated_at?: string
          vendor: string
        }
        Update: {
          ai_categorized?: boolean
          amount_cents?: number
          build_id?: string | null
          category?: string
          created_at?: string
          currency?: string
          external_id?: string | null
          id?: string
          is_recurring?: boolean
          notes?: string | null
          receipt_path?: string | null
          recurrence?: string | null
          source?: string
          spent_on?: string
          tax_deductible?: boolean | null
          updated_at?: string
          vendor?: string
        }
        Relationships: []
      }
      feedback: {
        Row: {
          build_id: string
          created_at: string
          detail: string | null
          id: string
          kind: string
          linked_ticket_id: string | null
          reporter_ref: string | null
          sentiment: string | null
          severity: string | null
          source: string
          status: string
          summary: string
          updated_at: string
        }
        Insert: {
          build_id: string
          created_at?: string
          detail?: string | null
          id?: string
          kind: string
          linked_ticket_id?: string | null
          reporter_ref?: string | null
          sentiment?: string | null
          severity?: string | null
          source: string
          status?: string
          summary: string
          updated_at?: string
        }
        Update: {
          build_id?: string
          created_at?: string
          detail?: string | null
          id?: string
          kind?: string
          linked_ticket_id?: string | null
          reporter_ref?: string | null
          sentiment?: string | null
          severity?: string | null
          source?: string
          status?: string
          summary?: string
          updated_at?: string
        }
        Relationships: []
      }
      learnings: {
        Row: {
          build_id: string | null
          created_at: string
          decision_id: string | null
          id: string
          lesson: string
          source_outcome: string | null
          tags: string[] | null
          weight: number
        }
        Insert: {
          build_id?: string | null
          created_at?: string
          decision_id?: string | null
          id?: string
          lesson: string
          source_outcome?: string | null
          tags?: string[] | null
          weight?: number
        }
        Update: {
          build_id?: string | null
          created_at?: string
          decision_id?: string | null
          id?: string
          lesson?: string
          source_outcome?: string | null
          tags?: string[] | null
          weight?: number
        }
        Relationships: []
      }
      member_invites: {
        Row: {
          avatar_color: string | null
          email: string
          full_name: string
          handle: string
          role: string
        }
        Insert: {
          avatar_color?: string | null
          email: string
          full_name: string
          handle: string
          role?: string
        }
        Update: {
          avatar_color?: string | null
          email?: string
          full_name?: string
          handle?: string
          role?: string
        }
        Relationships: []
      }
      members: {
        Row: {
          avatar_color: string | null
          created_at: string
          email: string
          full_name: string
          handle: string
          id: string
          is_active: boolean
          role: string
          updated_at: string
        }
        Insert: {
          avatar_color?: string | null
          created_at?: string
          email: string
          full_name: string
          handle: string
          id: string
          is_active?: boolean
          role?: string
          updated_at?: string
        }
        Update: {
          avatar_color?: string | null
          created_at?: string
          email?: string
          full_name?: string
          handle?: string
          id?: string
          is_active?: boolean
          role?: string
          updated_at?: string
        }
        Relationships: []
      }
      metric_snapshots: {
        Row: {
          build_id: string | null
          captured_on: string
          created_at: string
          id: string
          meta: Json | null
          metric: string
          value_num: number
        }
        Insert: {
          build_id?: string | null
          captured_on?: string
          created_at?: string
          id?: string
          meta?: Json | null
          metric: string
          value_num: number
        }
        Update: {
          build_id?: string | null
          captured_on?: string
          created_at?: string
          id?: string
          meta?: Json | null
          metric?: string
          value_num?: number
        }
        Relationships: []
      }
      // ── Added by migration 0016 (regenerate after deploy) ──
      repo_activity: {
        Row: {
          author: string | null
          build_id: string
          created_at: string
          external_id: string
          id: string
          kind: string
          occurred_at: string
          ref: string | null
          status: string | null
          title: string
          url: string | null
        }
        Insert: {
          author?: string | null
          build_id: string
          created_at?: string
          external_id: string
          id?: string
          kind: string
          occurred_at?: string
          ref?: string | null
          status?: string | null
          title: string
          url?: string | null
        }
        Update: {
          author?: string | null
          build_id?: string
          created_at?: string
          external_id?: string
          id?: string
          kind?: string
          occurred_at?: string
          ref?: string | null
          status?: string | null
          title?: string
          url?: string | null
        }
        Relationships: []
      }
      milestones: {
        Row: {
          build_id: string | null
          created_at: string
          description: string | null
          done_at: string | null
          id: string
          sort_order: number
          status: string
          target_date: string | null
          title: string
          unlocks: string | null
          updated_at: string
        }
        Insert: {
          build_id?: string | null
          created_at?: string
          description?: string | null
          done_at?: string | null
          id?: string
          sort_order?: number
          status?: string
          target_date?: string | null
          title: string
          unlocks?: string | null
          updated_at?: string
        }
        Update: {
          build_id?: string | null
          created_at?: string
          description?: string | null
          done_at?: string | null
          id?: string
          sort_order?: number
          status?: string
          target_date?: string | null
          title?: string
          unlocks?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      prospects: {
        Row: {
          booking_clicked: boolean
          build_id: string
          company: string
          contact_email: string | null
          contact_name: string | null
          created_at: string
          employee_count: number | null
          gmail_thread_id: string | null
          id: string
          last_touch_at: string | null
          location: string | null
          next_action: string | null
          next_action_due: string | null
          notes: string | null
          open_count: number
          reply_count: number
          segment: string | null
          signal: string | null
          source: string
          status: string
          updated_at: string
        }
        Insert: {
          booking_clicked?: boolean
          build_id: string
          company: string
          contact_email?: string | null
          contact_name?: string | null
          created_at?: string
          employee_count?: number | null
          gmail_thread_id?: string | null
          id?: string
          last_touch_at?: string | null
          location?: string | null
          next_action?: string | null
          next_action_due?: string | null
          notes?: string | null
          open_count?: number
          reply_count?: number
          segment?: string | null
          signal?: string | null
          source?: string
          status?: string
          updated_at?: string
        }
        Update: {
          booking_clicked?: boolean
          build_id?: string
          company?: string
          contact_email?: string | null
          contact_name?: string | null
          created_at?: string
          employee_count?: number | null
          gmail_thread_id?: string | null
          id?: string
          last_touch_at?: string | null
          location?: string | null
          next_action?: string | null
          next_action_due?: string | null
          notes?: string | null
          open_count?: number
          reply_count?: number
          segment?: string | null
          signal?: string | null
          source?: string
          status?: string
          updated_at?: string
        }
        Relationships: []
      }
      revenue_entries: {
        Row: {
          amount_cents: number
          build_id: string
          created_at: string
          currency: string
          customer_ref: string | null
          external_id: string | null
          id: string
          kind: string
          mrr_cents: number
          occurred_on: string
          source: string
          status: string
          updated_at: string
        }
        Insert: {
          amount_cents: number
          build_id: string
          created_at?: string
          currency?: string
          customer_ref?: string | null
          external_id?: string | null
          id?: string
          kind: string
          mrr_cents?: number
          occurred_on?: string
          source: string
          status?: string
          updated_at?: string
        }
        Update: {
          amount_cents?: number
          build_id?: string
          created_at?: string
          currency?: string
          customer_ref?: string | null
          external_id?: string | null
          id?: string
          kind?: string
          mrr_cents?: number
          occurred_on?: string
          source?: string
          status?: string
          updated_at?: string
        }
        Relationships: []
      }
      rules: {
        Row: {
          actions: Json
          build_scope: string
          conditions: Json
          config: Json
          created_at: string
          description: string | null
          id: string
          is_enabled: boolean
          name: string
          priority: number
          requires_approval: boolean
          trigger_event: string
          updated_at: string
        }
        Insert: {
          actions?: Json
          build_scope?: string
          conditions?: Json
          config?: Json
          created_at?: string
          description?: string | null
          id?: string
          is_enabled?: boolean
          name: string
          priority?: number
          requires_approval?: boolean
          trigger_event: string
          updated_at?: string
        }
        Update: {
          actions?: Json
          build_scope?: string
          conditions?: Json
          config?: Json
          created_at?: string
          description?: string | null
          id?: string
          is_enabled?: boolean
          name?: string
          priority?: number
          requires_approval?: boolean
          trigger_event?: string
          updated_at?: string
        }
        Relationships: []
      }
      tickets: {
        Row: {
          assignee: string | null
          blocks_milestone_id: string | null
          build_id: string
          closed_at: string | null
          created_at: string
          description: string | null
          estimate_minutes: number | null
          external_id: string | null
          external_url: string | null
          id: string
          is_blocker: boolean
          labels: string[] | null
          priority: string
          ref: string | null
          source: string
          stage: string
          stage_changed_at: string
          title: string
          type: string
          updated_at: string
        }
        Insert: {
          assignee?: string | null
          blocks_milestone_id?: string | null
          build_id: string
          closed_at?: string | null
          created_at?: string
          description?: string | null
          estimate_minutes?: number | null
          external_id?: string | null
          external_url?: string | null
          id?: string
          is_blocker?: boolean
          labels?: string[] | null
          priority?: string
          ref?: string | null
          source?: string
          stage?: string
          stage_changed_at?: string
          title: string
          type?: string
          updated_at?: string
        }
        Update: {
          assignee?: string | null
          blocks_milestone_id?: string | null
          build_id?: string
          closed_at?: string | null
          created_at?: string
          description?: string | null
          estimate_minutes?: number | null
          external_id?: string | null
          external_url?: string | null
          id?: string
          is_blocker?: boolean
          labels?: string[] | null
          priority?: string
          ref?: string | null
          source?: string
          stage?: string
          stage_changed_at?: string
          title?: string
          type?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: { [_ in never]: never }
    Functions: {
      advance_ticket: {
        Args: { p_ticket_id: string; p_to_stage: string }
        Returns: Database["public"]["Tables"]["tickets"]["Row"]
      }
      decide_approval: {
        Args: { p_approval_id: string; p_decision: string }
        Returns: Database["public"]["Tables"]["approvals"]["Row"]
      }
      is_founder: { Args: Record<string, never>; Returns: boolean }
      is_member: { Args: Record<string, never>; Returns: boolean }
      // ── Added by migration 0012 (regenerate after deploy) ──
      upsert_rule: {
        Args: {
          p_id: string | null
          p_name: string
          p_description: string | null
          p_trigger_event: string
          p_build_scope: string
          p_conditions: Json
          p_actions: Json
          p_requires_approval: boolean
          p_auto_approve_medium: boolean
          p_priority: number
          p_is_enabled: boolean
        }
        Returns: Database["public"]["Tables"]["rules"]["Row"]
      }
      set_rule_enabled: {
        Args: { p_id: string; p_enabled: boolean }
        Returns: Database["public"]["Tables"]["rules"]["Row"]
      }
      // ── Added by migration 0013 (regenerate after deploy) ──
      set_connection_secret: {
        Args: { p_provider: string; p_key_name: string; p_value: string }
        Returns: undefined
      }
      delete_connection_secret: {
        Args: { p_provider: string; p_key_name: string }
        Returns: undefined
      }
      set_connection: {
        Args: { p_provider: string; p_status: string | null; p_sync_frequency: string | null }
        Returns: Database["public"]["Tables"]["connections"]["Row"]
      }
      // ── Added by migration 0015 (regenerate after deploy) ──
      log_login: { Args: Record<string, never>; Returns: undefined }
      // ── Added by migration 0017 (regenerate after deploy) ──
      request_agent_run: { Args: { p_slug: string; p_input: Json }; Returns: undefined }
    }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}

type DefaultSchema = Database["public"]

export type Tables<T extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][T]["Row"]
export type TablesInsert<T extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][T]["Insert"]
export type TablesUpdate<T extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][T]["Update"]
